name: C++ CI with CMake (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure -C Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: MyApp
        path: build/Release/MyApp.exe